#pragma once
#include  "CoreMinimal.h"
#include "NativeGameplayTags.h"
#define LOCTEXT_NAMESPACE "GameplayTags"

namespace GamePlayTags
{
	
	//提示连击的标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MultiTipSign)
	//提示允许预输入的标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExecutePreInput)
	//提示立刻执行预输入的标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExecutePreInputImmediately)
	
	//状态标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ground)
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)
	
	
	//提示后摇的Tag
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PostAnim)
	
}
 #undef LOCTEXT_NAMESPACE