#pragma once
#include  "CoreMinimal.h"
#include "NativeGameplayTags.h"
#define LOCTEXT_NAMESPACE "GameplayTags"

namespace GamePlayTags
{
	//在这里定义所有的GameplayTag标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Move)
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Look)
	//提示连击的标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MultiTipSign)
	//提示允许预输入的标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExecutePreInput)
	//提示立刻执行预输入的标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ExecutePreInputImmediately)

	//状态标签
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ground)
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InAir)

	//Skill输入
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RelaxAttack)
	ACTIONSKILLASSETRUNTIME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HeavyAttack)
	
}
 #undef LOCTEXT_NAMESPACE