#pragma once
#include "NativeGameplayTags.h"
namespace ActionCameraTag
{

	ACTIONCAMERASYSTEMASSET_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NormalCamera)
	ACTIONCAMERASYSTEMASSET_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(CinemaCamera)
	
};
